spring:
  application:
    name: rest-api-example
  datasource:
    hikari:
      maximum-pool-size: 30
      connectionTimeout: 30000
      idleTimeout: 600000
      maxLifetime: 1800000 
  jpa: 
    properties: 
      hibernate: 
        id: 
          new_generator_mappings: false
        format_sql: true
        jdbc: 
          lob: 
            non_contextual_creation: true
        ddl-auto: validate
  h2:
    console:
      enabled: true
      path: /h2-console
      
  jackson:
    default-property-inclusion: NON_NULL

logging: 
  level: 
    org: 
      hibernate: 
        SQL: DEBUG
      type: 
        descriptor: 
        sql: 
          BasicBinder: TRACE

security:
  basic:
    enable: false

---      
##################################### DEV ENVIRONMENT PROFILE ##################################### 

server:
  port: 8085

spring:
  application:
    name: rest-api-example-dev
  profiles: dev
  
  datasource:
    url: jdbc:h2:mem:test